file:
  ReadPath: C:\Users\Desktop\SFTP\Outbound\payment_Processing.csv
  WritePath: C:\Users\Desktop\SFTP\Inbound\sftpData.csv
  ArchivePath : C:\Users\Desktop\SFTP\Archive
  outbound: C:\Users\Desktop\SFTP\Outbound
  matcher : '*.csv'

db:
  host: localhost
  port: "3306"
  user: root
  password: root
  database: Mulesoft

salesforce:
  username: username@yourcompany.com
  password: Password
  token: tokenkey

email:
  host: smtp.gmail.com
  port: "587"
  user: username@gmail.com
  password: password
  
SalesForceError : "SalesForceError"
FileError : "FileError"
DataBaseError : "DataBaseError"
