[
  {
    "Emp_Id": "1111",
    "First_Name": "Daniel",
    "Last_Name": "White",
    "Date_of_Birth": "1965-11-10",
    "Joining_Date": "2023-01-01",
    "Termination_Date": "",
    "Employee_Status": "Terminated",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787866",
    "Address": "Flat No 001 Fake Street Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1112",
    "First_Name": "Austin",
    "Last_Name": "James",
    "Date_of_Birth": "1967-08-15",
    "Joining_Date": "2023-01-02",
    "Termination_Date": "",
    "Employee_Status": "Terminated",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787896",
    "Address": "Flat No 002 Fake Street Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1113",
    "First_Name": "Peter",
    "Last_Name": "Carolina",
    "Date_of_Birth": "1969-05-19",
    "Joining_Date": "2023-01-03",
    "Termination_Date": "",
    "Employee_Status": "Employeed",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787926",
    "Address": "Flat No 001 Fake Street Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1114",
    "First_Name": "Glenn",
    "Last_Name": "Bison",
    "Date_of_Birth": "1971-02-21",
    "Joining_Date": "2023-01-04",
    "Termination_Date": "",
    "Employee_Status": "Employeed",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787956",
    "Address": "Flat No 002 Fake Street Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1115",
    "First_Name": "Mark",
    "Last_Name": "Henry",
    "Date_of_Birth": "1972-11-25",
    "Joining_Date": "2001-02-26",
    "Termination_Date": "",
    "Employee_Status": "Employeed",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787986",
    "Address": "Flat No 001 Fake Street Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1116",
    "First_Name": "Sadio",
    "Last_Name": "Mane",
    "Date_of_Birth": "1998-10-02",
    "Joining_Date": "2001-02-27",
    "Termination_Date": "",
    "Employee_Status": "Employeed",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787987",
    "Address": "Flat No 001 Fake Street Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1117",
    "First_Name": "Ronaldinho",
    "Last_Name": "Gacha",
    "Date_of_Birth": "1962-11-25",
    "Joining_Date": "2001-02-28",
    "Termination_Date": "",
    "Employee_Status": "Employeed",
    "Payment_Status": "Payment Pending",
    "Phone_Number": "9898787988",
    "Address": "Flat No 001 Fake Street Pune",
    "Status": ""
  }
]