file:
  ReadPath: C:\Users\primahar\OneDrive - Capgemini\Desktop\SFTP\Outbound\payment_Processing.csv
  WritePath: C:\Users\primahar\OneDrive - Capgemini\Desktop\SFTP\Inbound\sftpData.csv
  ArchivePath : C:\Users\primahar\OneDrive - Capgemini\Desktop\SFTP\Archive
  Outbound : C:\Users\primahar\OneDrive - Capgemini\Desktop\SFTP\Outbound\Excluded\\
  filePath : C:\Users\primahar\OneDrive - Capgemini\Desktop\SFTP
  sftp: C:\Users\primahar\OneDrive - Capgemini\Desktop\SFTP\Inboundd\sftpData.csv

db:
  host: localhost
  port: "3306"
  user: root
  password: root
  database: Mulesoft

salesforce:
  username: priyamn@mycompany.com
  password: Priya1998!
  token: FBKnPmviP2eKJcyWoQBjTFnq

cron:
  job: "0 0 0 15 * ?"
  
email:
  host: smtp.gmail.com
  port: "587"
  user: iampriyamn@gmail.com
  password: vzwkmavcqhbhyalt